export default {
  STRING: "STRING",
  TEXT: "TEXT",
  DATE: "DATE",
  DATETIME: "DATETIME",
  BOOLEAN: "BOOLEAN",
  NUMBER: "NUMBER",
  INTEGER: "INTEGER",
  USER: "USER",
  GROUP: "GROUP",
  FORMULA: "FORMULA",
  SELECT: "SELEC",
  ENTITY: "ENTITY"
};
